# Copyright (c) 2026 Simon Peter
#
# SPDX-License-Identifier: BSD-2-Clause

include $(GNUSTEP_MAKEFILES)/common.make

APP_NAME = panehost
panehost_OBJC_FILES = panehost.m
panehost_PRINCIPAL_CLASS = NSApplication
ADDITIONAL_GUI_LIBS += -lPreferencePanes
ADDITIONAL_OBJCFLAGS += -Wall

include $(GNUSTEP_MAKEFILES)/application.make
